### ISSUE TITLE
Bug: Unable to define schemes in bzl files

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/rules_xcodeproj#1056]
## Describe the bug
```
ERROR: Traceback (most recent call last):
        File "/Users/user/rules_xcodeproj/examples/ios_app/xcodeproj_targets.bzl", line 18, column 52, in <toplevel>
                launch_action = xcode_schemes.launch_action("//Example"),
        File "/private/var/tmp/_bazel_user/5d972cee451cda0f8ee319a467b3aff5/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcode_schemes.bzl", line 255, column 44, in _launch_action
                target = bazel_labels.normalize(target),
        File "/private/var/tmp/_bazel_user/5d972cee451cda0f8ee319a467b3aff5/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/bazel_labels.bzl", line 90, column 23, in _normalize
                parts = _parse(value)
        File "/private/var/tmp/_bazel_user/5d972cee451cda0f8ee319a467b3aff5/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/bazel_labels.bzl", line 54, column 65, in _parse
                repo_name = workspace_name_resolvers.repository_name()
Error in repository_name: The native module can be accessed only from a BUILD thread. Wrap the function in a macro and call it from a BUILD file
ERROR: Skipping 'xcodeproj': error loading package '': initialization of module 'xcodeproj_targets.bzl' failed
WARNING: Target pattern parsing failed.
ERROR: error loading package '': initialization of module 'xcodeproj_targets.bzl' failed
INFO: Elapsed time: 0.216s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

## Reproduction steps
1. Apply these changes to the current repository:
```diff
diff --git i/examples/ios_app/BUILD w/examples/ios_app/BUILD
index c35f6b9b..5e0a2ede 100644
--- i/examples/ios_app/BUILD
+++ w/examples/ios_app/BUILD
@@ -1,10 +1,11 @@
 load("@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:xcodeproj.bzl", "xcodeproj")
-load(":xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")
+load(":xcodeproj_targets.bzl", "XCODEPROJ_TARGETS", "XCODE_SCHEMES")
 
 xcodeproj(
     name = "xcodeproj",
     build_mode = "xcode",
     project_name = "iOS App",
+    schemes = XCODE_SCHEMES,
     tags = ["manual"],
     top_level_targets = XCODEPROJ_TARGETS,
 )
diff --git i/examples/ios_app/xcodeproj_targets.bzl w/examples/ios_app/xcodeproj_targets.bzl
index 9126a025..f0fcd9ca 100644
--- i/examples/ios_app/xcodeproj_targets.bzl
+++ w/examples/ios_app/xcodeproj_targets.bzl
@@ -1,8 +1,20 @@
 """Exposes targets used by `xcodeproj` to allow use in fixture tests."""
 
+load(
+    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:xcodeproj.bzl",
+    "xcode_schemes",
+)
+
 XCODEPROJ_TARGETS = [
     "//Example",
     "//ExampleTests",
     "//ExampleObjcTests",
     "//ExampleUITests",
 ]
+
+XCODE_SCHEMES = [
+    xcode_schemes.scheme(
+        name = "Example",
+        launch_action = xcode_schemes.launch_action("//Example"),
+    ),
+]
```

2. Run
```
cd examples/ios_app
bazel run xcodeproj
```

## Versions
- rules_xcodeproj: https://github.com/buildbuddy-io/rules_xcodeproj/commit/f201b91014dbc2090cb383f26aa21726a93d9373

**Comment by brentleyjones** [comment]
Currently expected. You need to put them in a function instead for now: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/doc/faq.md#why-does-toolsgenerator-declare-its-custom-xcode-schemes-in-a-function.
