### ISSUE TITLE
Feature Request: First class support for Bazel's remote capabilities (i.e. BES/RBC/RBE)

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/rules_xcodeproj#1116]
Currently you can add BES, RBC, or RBE globally or to the `rules_xcodeproj` Bazel configs in your `.bazelrc` file. This generally works well, but Bazel doesn't handle connectivity issues gracefully, and will fail builds if it can't connect to BES, or slow them down at the start if it can't connect to RBC/RBE:

```
Caused by: java.net.UnknownHostException: remote.buildbuddy.io
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 5 more

ERROR: Failed to query remote execution capabilities: UNAVAILABLE: Unable to resolve host remote.buildbuddy.io
```

We should add first class support for for Bazel's remote capabilities:

- [ ] Allow specifying one or more configs for these features
- [ ] Do connectivity or health checks on the endpoints, and only supply them if they pass
- [ ] Anything else?

**Comment by brentleyjones** [comment]
I think this would instead be best handled by something like the [BuildBuddy CLI](https://www.buildbuddy.io/cli/).
