### ISSUE TITLE
Bug: Builds relying on `apple_dynamic_xcframework` fail BwB builds

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#1224]
## Describe the bug

Building an app with BwB that uses `apple_dynamic_xcframework` fails at analysis, assuming `apple_dynamic_xcframework`'s inference of platform IDs is relied on.

```
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ekerber/dd323d2a4ff53820c11ccc0d5aebe791/external/build_bazel_rules_apple/apple/internal/apple_framework_import.bzl", line 712, column 49, in _apple_dynamic_xcframework_import_impl
                return _common_dynamic_framework_import_impl(ctx, is_xcframework = True)
        File "/private/var/tmp/_bazel_ekerber/dd323d2a4ff53820c11ccc0d5aebe791/external/build_bazel_rules_apple/apple/internal/apple_framework_import.bzl", line 482, column 63, in _common_dynamic_framework_import_impl
                _, _, framework_imports = _process_xcframework_imports(ctx)
        File "/private/var/tmp/_bazel_ekerber/dd323d2a4ff53820c11ccc0d5aebe791/external/build_bazel_rules_apple/apple/internal/apple_framework_import.bzl", line 456, column 13, in _process_xcframework_imports
                fail("Failed to figure out library identifiers. Please provide a " +
Error in fail: Failed to figure out library identifiers. Please provide a dictionary of library identifiers to `library_identifiers`.

```

Likely reproduces after https://github.com/buildbuddy-io/rules_xcodeproj/pull/1131

## Reproduction steps

- Depend on `apple_dynamic_xcframework`
- Build with BwB
- 
## Expected behavior

☀️ 

## Versions
- Bazel: 6.0.0-pre.20220922.1
- rules_xcodeproj: 615330cacc35a5a87b7f315424ded30fb4d165ad
- rules_apple: 1.1.2
- rules_swift: 1.2.0

**Comment by brentleyjones** [comment]
@thii I think we will have to revert #1131.

**Comment by brentleyjones** [comment]
I'm going to revert #1131, and work to get a solution into the BB UI that allows seeing the targets built.

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/buildbuddy/pull/2663 will allow us to fix the display in BuildBuddy.
