### ISSUE TITLE
Bug: `apple_universal_binary` fails project generation

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/rules_xcodeproj#1410]
Changed a target to an `apple_univeral_binary` from a `macos_command_line_application` and saw this error:

```bash
ERROR: /Users/buildkite/builds/mbr-buildkite-agent-ios-prod-bcer-1/slack/ios-pull-request/tooling/needle/BUILD.bazel:18:23: in @com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:default_automatic_target_processing_aspect.bzl%default_automatic_target_processing_aspect,@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:xcodeproj_aspect.bzl%xcodeproj_aspect aspect on apple_universal_binary rule //tooling/needle:detector: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/7a258e1e8c20cba7a42ee679660a55e6/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeproj_aspect.bzl", line 58, column 33, in _xcodeproj_aspect_impl
		create_xcodeprojinfo(
	File "/private/var/tmp/_bazel_buildkite/7a258e1e8c20cba7a42ee679660a55e6/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 474, column 35, in create_xcodeprojinfo
		info_fields = _skip_target(
	File "/private/var/tmp/_bazel_buildkite/7a258e1e8c20cba7a42ee679660a55e6/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 263, column 36, in _skip_target
		_create_envs_depset(
	File "/private/var/tmp/_bazel_buildkite/7a258e1e8c20cba7a42ee679660a55e6/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 292, column 23, in _create_envs_depset
		test_env = getattr(ctx.rule.attr, automatic_target_info.env, {})
Error in getattr: in call to getattr(), parameter 'name' got value of type 'NoneType', want 'string'
```

I haven't looked too deep into it but noticed there was no sibling issue for this from #99

**Comment by brentleyjones** [comment]
Yeah, it's not supported right now. Even before that breakage, there are oddities with transitions, and the multiple archs, that make it so you currently only want to include the underlying binary in rules_xcodeproj. See `generator` for an example: https://github.com/buildbuddy-io/rules_xcodeproj/blob/0ad6162d7c97e218d07c4892b864ceaaff150e5a/tools/generator/BUILD#L33-L62

**Comment by erikkerber** [comment]
This is for any tool that is used within the build graph of any `top_level_target`, and in our case is used to generate code.

We'll want it universal and traversed in rules_xcodeproj, just likely removing the source of the error without needing to support an Xcode target with a universal_binary.

**Comment by brentleyjones** [comment]
I changed the title, since your fix will prevent the generation failure, but it won't add full support for it per the discussion above. I'll add a new issue for fully supporting it.
