### ISSUE TITLE
Bug: Error generating rules_ios VFS targets in BwB mode using 0.12.2

### ISSUE THREAD

**Issue by luispadron** [buildbuddy-io/rules_xcodeproj#1618]
## Describe the bug

Using version 0.12.2 when generating a BwB xcode project target that depends on a `top_level_target` that is a `rules_ios` `ios_application` target. 

When running generation we receive this error:

```sh
ERROR: /Users/lpadron/Development/cash-ios/Code/NonEmpty/BUILD.bazel:12:15: in @com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:default_automatic_target_processing_aspect.bzl%default_automatic_target_processing_aspect,@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:xcodeproj_rule.bzl%bwb_xcodeproj_aspect aspect on apple_framework_packaging rule //Code/NonEmpty:NonEmpty: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_lpadron/9ae9416857eb79bb978de35a53d54970/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeproj_aspect.bzl", line 56, column 36, in _xcodeproj_aspect_impl
                info = create_xcodeprojinfo(
        File "/private/var/tmp/_bazel_lpadron/9ae9416857eb79bb978de35a53d54970/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 565, column 44, in create_xcodeprojinfo
                info_fields = _create_xcodeprojinfo(
        File "/private/var/tmp/_bazel_lpadron/9ae9416857eb79bb978de35a53d54970/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 507, column 31, in _create_xcodeprojinfo
                xcode_targets = depset(
Error in depset: depset elements must not be mutable values
ERROR: Analysis of target '//Code/App:Xcode.generator' failed; build aborted: 
```

## Reproduction steps
- Define an Xcode project target
- Add top_level target that uses rules_ios `ios_application`
- Enable `--features apple.virtualize_frameworks`
- Run the generator

## Expected behavior
- Generation succeeds

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 0.12.2
- rules_apple: 2.0.0
- rules_swift: 1.5.1

**Comment by brentleyjones** [comment]
I believe this bug is fixed on `main`.

**Comment by luispadron** [comment]
Checking!

**Comment by luispadron** [comment]
Yep this is fixed in main! Seeing another issue so i'll follow up about that one
