### ISSUE TITLE
Bug: `Error in depset: cannot add an item of type 'NoneType' to a depset of 'File'`

### ISSUE THREAD

**Issue by achew22** [buildbuddy-io/rules_xcodeproj#555]
## Describe the bug

When depending on a `rules_spm` copy of `swift-nio`, upon building an xcodeproj, I get the following error:

```
➜  repo bazel run //:xcodeproj
ERROR: /private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/swift_pkgs/swift-nio/BUILD.bazel:51:18: in @com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:default_input_file_attributes_aspect.bzl%default_input_file_attributes_aspect,@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj/internal:xcodeproj_aspect.bzl%xcodeproj_aspect aspect on swift_import rule @swift_pkgs//swift-nio:_NIODataStructures:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeproj_aspect.bzl", line 47, column 33, in _xcodeproj_aspect_impl
                create_xcodeprojinfo(
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 288, column 44, in create_xcodeprojinfo
                info_fields = _create_xcodeprojinfo(
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 223, column 50, in _create_xcodeprojinfo
                processed_target = process_library_target(
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/library_targets.bzl", line 150, column 35, in process_library_target
                outputs = output_files.collect(
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/output_files.bzl", line 233, column 19, in _collect
                return _create(
        File "/private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/output_files.bzl", line 57, column 30, in _create
                transitive_build = depset(
Error in depset: cannot add an item of type 'NoneType' to a depset of 'File'
ERROR: Analysis of target '//:xcodeproj' failed; build aborted:
INFO: Elapsed time: 0.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 15 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 15 targets configured)
```

## Reproduction steps

`WORKSPACE`

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_github_buildbuddy_io_rules_xcodeproj",
    # Current as of June 16, 2022.
    commit = "85d5b31a5d2c9f686a6ac403475d3b508bc737fc",
    remote = "https://github.com/buildbuddy-io/rules_xcodeproj",
)

load(
    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:repositories.bzl",
    "xcodeproj_rules_dependencies",
)

xcodeproj_rules_dependencies()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "cgrindel_rules_spm",
    sha256 = "ba4310ba33cd1864a95e41d1ceceaa057e56ebbe311f74105774d526d68e2a0d",
    strip_prefix = "rules_spm-0.10.0",
    urls = [
        "http://github.com/cgrindel/rules_spm/archive/v0.10.0.tar.gz",
    ],
)

load(
    "@cgrindel_rules_spm//spm:deps.bzl",
    "spm_rules_dependencies",
)

spm_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load("@cgrindel_rules_spm//spm:defs.bzl", "spm_pkg", "spm_repositories")

spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/apple/swift-nio.git",
            exact_version = "2.40.0",
            products = ["NIOPosix"], # Can't directly depend on _NIODataStructures, and NIOPosix contains it
        ),
    ],
    platforms = [
        ".iOS(.v14)",
        ".macOS(.v10_15)",
    ],
)
```

`BUILD`

```
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load(
    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:xcodeproj.bzl",
    "xcodeproj",
)

swift_library(
    name = "Lib",
    srcs = glob(["**/*.swift"]),
    deps = ["@swift_pkgs//swift-nio:_NIODataStructures"],
)

ios_application(
    name = "App",
    bundle_id = "com.example.app",
    families = ["iphone", "ipad"],
    infoplists = [":Info.plist"],
    minimum_os_version = "15.0",
    deps = [":Lib"],
)

xcodeproj(
    name = "xcodeproj",
    project_name = "App",
    targets = [
        ":App",
    ],
    tags = ["manual"],
)
```

then `touch test.swift` so that there is something to let the `swift_library`continue.

## Expected behavior

Get an XCode project output.

## Versions
- Bazel (by way of Bazelisk):
   - Bazelisk version: development
   - Build label: 5.2.0
   - Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
   - Build time: Tue Jun 7 16:11:09 2022 (1654618269)
   - Build timestamp: 1654618269
   - Build timestamp as int: 1654618269
- rules_xcodeproj: `85d5b31a5d2c9f686a6ac403475d3b508bc737fc`
- rules_apple: [`029eab0a6bbb4147d227d623721b205eb62aca9c`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/85d5b31a5d2c9f686a6ac403475d3b508bc737fc/xcodeproj/repositories.bzl#L85-L93)
- rules_swift: [`8d4b096b90e47095755e47c27e749ae9b9f83e81`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/85d5b31a5d2c9f686a6ac403475d3b508bc737fc/xcodeproj/repositories.bzl#L75-L83)

## Additional context

Happy to provide any more information you think would be helpful.

**Comment by achew22** [comment]
Oops! I forgot to include the definition that `rules_spm` had for the target:

```
➜  repo bazel query --output=build @swift_pkgs//swift-nio:_NIODataStructures
# /private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/swift_pkgs/swift-nio/BUILD.bazel:51:18
swift_import(
  name = "_NIODataStructures",
  visibility = ["//visibility:public"],
  generator_name = "_NIODataStructures",
  generator_function = "spm_swift_library",
  generator_location = "swift-nio/BUILD.bazel:51:18",
  deps = [],
  archives = ["@swift_pkgs//swift-nio:_NIODataStructures_a_file"],
  module_name = "_NIODataStructures",
  swiftdoc = "@swift_pkgs//swift-nio:_NIODataStructures_swiftdoc",
  swiftmodule = "@swift_pkgs//swift-nio:_NIODataStructures_swiftmodule",
)
# Rule _NIODataStructures instantiated at (most recent call last):
#   /private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/swift_pkgs/swift-nio/BUILD.bazel:51:18                     in <toplevel>
#   /private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/cgrindel_rules_spm/spm/private/spm_swift_library.bzl:50:17 in spm_swift_library
# Rule swift_import defined at (most recent call last):
#   /private/var/tmp/_bazel_achew/3b38b66c662b8772988ae3de9dafda8e/external/build_bazel_rules_swift/swift/internal/swift_import.bzl:104:20 in <toplevel>
```

**Comment by brentleyjones** [comment]
Thanks for the detailed bug report! The goal of the next release is to fix things like this. I'll be sure to address this bug as part of that work.

**Comment by achew22** [comment]
Looking at this, I think this is actually an FR for https://github.com/buildbuddy-io/rules_xcodeproj/issues/90. Sorry for the noise! I'll leave it open because it makes reproducing easier, but feel free to close if you think the other bug is better.

**Comment by brentleyjones** [comment]
I like that it make reproducing easier, and gives me something to close with a PR 😄.
