### ISSUE TITLE
Bug: toolchain_utils.bzl error with --incompatible_enable_cc_toolchain_resolution

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#755]
## Describe the bug
When running an xcodeproj target with `--incompatible_enable_cc_toolchain_resolution`, execution fails with the following error:

```
ERROR: /private/var/tmp/_bazel_johnfirebaugh/de81c63101cf328cf2403625a48dbb16/external/local_config_cc/BUILD:84:24: in //xcodeproj/internal:default_automatic_target_processing_aspect.bzl%default_automatic_target_processing_aspect,//xcodeproj/internal:xcodeproj_aspect.bzl%xcodeproj_aspect aspect on cc_toolchain_config rule @local_config_cc//:ios_x86_64: 
Traceback (most recent call last):
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/xcodeproj_aspect.bzl", line 47, column 33, in _xcodeproj_aspect_impl
		create_xcodeprojinfo(
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 414, column 44, in create_xcodeprojinfo
		info_fields = _create_xcodeprojinfo(
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 266, column 52, in _create_xcodeprojinfo
		processed_target = process_top_level_target(
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/top_level_targets.bzl", line 316, column 47, in process_top_level_target
		linker_inputs = linker_input_files.collect(
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/linker_input_files.bzl", line 45, column 53, in _collect
		top_level_values = _extract_top_level_values(
	File "/Users/john/figma/rules_xcodeproj/xcodeproj/internal/linker_input_files.bzl", line 191, column 42, in _extract_top_level_values
		cc_toolchain = find_cpp_toolchain(ctx)
	File "/private/var/tmp/_bazel_johnfirebaugh/de81c63101cf328cf2403625a48dbb16/external/bazel_tools/tools/cpp/toolchain_utils.bzl", line 41, column 17, in find_cpp_toolchain
		fail("In order to use find_cpp_toolchain, you must include the '%s' in the toolchains argument to your rule." % CPP_TOOLCHAIN_TYPE)
Error in fail: In order to use find_cpp_toolchain, you must include the '@bazel_tools//tools/cpp:toolchain_type' in the toolchains argument to your rule.
ERROR: Analysis of target '//examples/simple:xcodeproj' failed; build aborted: 
```

## Reproduction steps
In the rules_xcodeproj repository, run `bazel run --incompatible_enable_cc_toolchain_resolution //examples/simple:xcodeproj`.

## Expected behavior
It executes successfully.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: Revision 75320b55941087f6a0eb0d75d2859857fe91e738
- rules_apple: Installed by rules_xcodeproj at above revision
- rules_swift: Installed by rules_xcodeproj at above revision

## Additional context
This upstream issue seems related: https://github.com/bazelbuild/bazel/issues/6874.

**Comment by jfirebaugh** [comment]
Thanks for the quick fix! I confirmed it works in my project.
